<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="0" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-24T16:06:08 IST" name="Default suite" finished-at="2022-06-24T16:09:48 IST" duration-ms="219944">
    <groups>
    </groups>
    <test started-at="2022-06-24T16:06:08 IST" name="Default test" finished-at="2022-06-24T16:09:48 IST" duration-ms="219944">
      <class name="com.crm.contactOrg.CreateContactsTest">
        <test-method is-config="true" signature="dbConnect()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:08 IST" name="dbConnect" finished-at="2022-06-24T16:06:08 IST" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbConnect -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:10 IST" name="launchBrowser" finished-at="2022-06-24T16:06:21 IST" duration-ms="11256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:21 IST" name="loginToAppln" finished-at="2022-06-24T16:06:34 IST" duration-ms="12920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:34 IST" name="createContactTest" finished-at="2022-06-24T16:06:50 IST" duration-ms="16246" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactOrg.CreateContactsTest.createContactTest(CreateContactsTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logOutFromApplication()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:50 IST" name="logOutFromApplication" finished-at="2022-06-24T16:06:54 IST" duration-ms="3385" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:06:54 IST" name="loginToAppln" finished-at="2022-06-24T16:07:16 IST" duration-ms="22288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:07:16 IST" name="createContactTest" finished-at="2022-06-24T16:07:28 IST" duration-ms="12429" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactOrg.CreateContactsTest.createContactTest(CreateContactsTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logOutFromApplication()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:07:28 IST" name="logOutFromApplication" finished-at="2022-06-24T16:07:34 IST" duration-ms="6072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:07:34 IST" name="loginToAppln" finished-at="2022-06-24T16:08:00 IST" duration-ms="25492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:08:00 IST" name="createContactTest" finished-at="2022-06-24T16:08:13 IST" duration-ms="13526" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactOrg.CreateContactsTest.createContactTest(CreateContactsTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logOutFromApplication()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:08:13 IST" name="logOutFromApplication" finished-at="2022-06-24T16:08:20 IST" duration-ms="6721" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:08:20 IST" name="loginToAppln" finished-at="2022-06-24T16:08:41 IST" duration-ms="21149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method retried="true" signature="createContactTest()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:08:41 IST" name="createContactTest" finished-at="2022-06-24T16:08:57 IST" duration-ms="16182" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactOrg.CreateContactsTest.createContactTest(CreateContactsTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logOutFromApplication()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:08:57 IST" name="logOutFromApplication" finished-at="2022-06-24T16:09:05 IST" duration-ms="7814" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method is-config="true" signature="loginToAppln()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:09:05 IST" name="loginToAppln" finished-at="2022-06-24T16:09:28 IST" duration-ms="23151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppln -->
        <test-method signature="createContactTest()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:09:28 IST" name="createContactTest" finished-at="2022-06-24T16:09:40 IST" duration-ms="11298" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactOrg.CreateContactsTest.createContactTest(CreateContactsTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContactTest -->
        <test-method is-config="true" signature="logOutFromApplication()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:09:40 IST" name="logOutFromApplication" finished-at="2022-06-24T16:09:48 IST" duration-ms="7086" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromApplication -->
        <test-method is-config="true" signature="closeTheBrowser()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:09:48 IST" name="closeTheBrowser" finished-at="2022-06-24T16:09:48 IST" duration-ms="608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTheBrowser -->
        <test-method is-config="true" signature="closeDBConfig()[pri:0, instance:com.crm.contactOrg.CreateContactsTest@957e06]" started-at="2022-06-24T16:09:50 IST" name="closeDBConfig" finished-at="2022-06-24T16:09:50 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConfig -->
      </class> <!-- com.crm.contactOrg.CreateContactsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
